### PR TITLE
Fix the name of ``TestClock``, upgrade code and release new version

### PR DESCRIPTION
**Pull request by DanielNoord**
Closes https://github.com/channable/opnieuw/issues/18.

Decided to release `2.0.0` as this is probably considered a breaking change.

### CODE REVIEW

**Comment by DanielNoord** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @DanielNoord, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 734eb22147c4fa6da6956e85fa9b0f453b0eec69, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/8bd55eee-48bb-43dc-a4ad-c5334c480fd0?pipeline_id=24f1637e-cfb8-45bd-b4a8-1d50d6041fd3) started.

**Pull request merged**
