### PR TITLE
Take control of randomness during tests

### PR DESCRIPTION
**Pull request by DanielNoord**
Fixes the flakiness we see in CI where we choose `0,0` randomly three times in a row.

### CODE REVIEW

**Review by jochemb — APPROVED** [review]
Thanks! Much faster tests too!

**Comment by DanielNoord** [comment]
@OpsBotPrime merge on friday

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @DanielNoord, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 460bf28a59080fee3a8495b4386efc432b73db3e, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/d9c1683f-a6f2-4ecb-ae02-c301b185624e?pipeline_id=60af3e11-e77e-470f-87a6-b88d96cea102) started.

**Pull request merged**
