### PR TITLE
Bump version to ``1.2.1``

### PR DESCRIPTION
**Pull request by DanielNoord**
This just includes a typing change and some clean up.
This is why I made this a patch release.

### CODE REVIEW

**Comment by DanielNoord** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @DanielNoord, rebasing now.

**Comment by OpsBotPrime** [comment]
Failed to rebase, please rebase manually using

    git fetch && git rebase --interactive --autosquash origin/master DanielNoord-patch-1

**Comment by DanielNoord** [comment]
How...

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @DanielNoord, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as d81b0f5602d966a5bbed0196c820e9f4be914b79, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/e9a6b49e-1e77-40e2-a7a6-78025fcd3e71?pipeline_id=e1309303-ce22-4e23-9d2a-8e5cbde5a267) started.

**Pull request merged**
