### PR TITLE
Refactor code slightly and add a changelog

### PR DESCRIPTION
**Pull request by DanielNoord**

### CODE REVIEW

**Review by Gijsvs — APPROVED** [review]

**Comment by OpsBotPrime** [comment]
Rebased as a6e01e480399558fc973b8d59e61b364dbb947ed, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/82079e12-98a5-48a8-8f07-9aae1d8d84ec?pipeline_id=465c82e7-aa88-4398-9de7-88816921a965) started.

**Comment by OpsBotPrime** [comment]
The [build failed :x:](https://channable.semaphoreci.com/workflows/82079e12-98a5-48a8-8f07-9aae1d8d84ec?pipeline_id=465c82e7-aa88-4398-9de7-88816921a965).

If this is the result of a flaky test, then tag me again with the `retry` command.  Otherwise, push a new commit and tag me again.

**Comment by DanielNoord** [comment]
@OpsBotPrime merge on friday

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @DanielNoord, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as d410522e4d9bfd78c6c289c7834978bdca78cf7d, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/2e48b7c8-bc99-4cdd-a531-34642b5fd441?pipeline_id=edc666fc-2f44-4a5d-a378-1b40f0843f1d) started.

**Pull request merged**
